########################################## begin goldberg ##########################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldberg  # https://en.wikipedia.org/wiki/Adele_Goldberg_(computer_scientist)
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goldberg
  template:
    metadata:
      labels:
        app: goldberg
    spec:
      containers:
      - image: ghcr.io/hlesey/flags:<FIXME>
        name: flags
      volumes:
      - name: config
        configMap:
          name: cm-goldberg
########################################## end ##########################################

####################################### begin idun ######################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idun # https://en.wikipedia.org/wiki/Iðunn
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idun
  template:
    metadata:
      labels:
        app: idun
    spec:
      containers:
      - name: flags
        image: ghcr.io/hlesey/flags:1.0
        args:
          - --config=/app/config/config.yaml
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: cm-idun
      securityContext:
        runAsUser: 1000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-idun
  namespace: ctf
data:
  config.yaml: |-
    hashes:
      alg: 2
########################################## end ##########################################

###################################### begin clarke #####################################
---
apiVersion: v1
kind: Pod
metadata:
  name: clarke  # https://en.wikipedia.org/wiki/Joan_Clarke
  namespace: ctf
spec:
  containers:
    - name: flags
      image: ghcr.io/hlesey/flags:1.0
      args:
        - --config=/app/config/config.yaml
      volumeMounts:
      - name: config
        mountPath: /app/config
  volumes:
    - name: config
      configMap:
        name: cm-clarke
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-clarke
  namespace: ctf
data:
  config.yaml: |-
    server:
      initialDelay: 10
    hashes:
      alg: 1
      min: 10
      max: 20
    stressTest:
      runStress: true
      memTotal: 64Mi
      memStepSize: 16Mi
########################################## end ##########################################

###################################### begin darwin #####################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: darwin  # https://en.wikipedia.org/wiki/Charles_Darwin
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: darwin
  template:
    metadata:
      labels:
        app: darwin
    spec:
      containers:
        - name: flags
          image: ghcr.io/hlesey/flags:1.0
          args:
            - --config=/app/config/config.yaml
          volumeMounts:
          - name: config
            mountPath: /app/config
      initContainers:
      - name: init-darwin
        image: ghcr.io/hlesey/busybox:latest
        command: ['sh', '-c', 'until nslookup darwin; do echo waiting for myservice; sleep 2; done;']
      volumes:
        - name: config
          configMap:
            name: cm-darwin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-darwin
  namespace: ctf
data:
  config.yaml: |-
    hashes:
      alg: 2
########################################## end ##########################################

##################################### begin dijkstra ####################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dijkstra  # https://en.wikipedia.org/wiki/Edsger_W._Dijkstra
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dijkstra
  template:
    metadata:
      labels:
        app: dijkstra
    spec:
      containers:
        - name: flags
          image: ghcr.io/hlesey/flags:1.0
          args:
            - --config=/app/config/config.yaml
          volumeMounts:
          - name: config
            mountPath: /app/config
          readinessProbe:
            httpGet:
              path: /
              port: 80
      volumes:
        - name: config
          configMap:
            name: cm-dijkstra
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-dijkstra
  namespace: ctf
data:
  config.yaml: |-
    hashes:
      alg: 4
########################################## end ##########################################

####################################### begin euler ####################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: euler  #  https://de.wikipedia.org/wiki/Leonhard_Euler
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: euler
  template:
    metadata:
      labels:
        app: euler
    spec:
      nodeSelector:
        wrong-node-selector: "true"
      containers:
        - name: flags
          image: ghcr.io/hlesey/flags:1.0
          args:
            - --config=/app/config/config.yaml
          volumeMounts:
          - name: config
            mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: cm-euler
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-euler
  namespace: ctf
data:
  config.yaml: |-
    hashes:
      alg: 2
      min: 20
      max: 30
########################################## end ##########################################

###################################### begin banach #####################################
---
apiVersion: batch/v1
kind: Job
metadata:
  name: banach  # https://en.wikipedia.org/wiki/Stefan_Banach
  namespace: ctf
spec:
  template:
    spec:
      containers:
        - name: flags
          image: ghcr.io/hlesey/flags:1.0
          args:
            - --config=/app/config/config.yaml
          volumeMounts:
          - name: config
            mountPath: /app/config
      restartPolicy: Never
      volumes:
        - name: config
          configMap:
            name: cm-banach
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-banach
  namespace: ctf
data:
  config.yaml: |-
    server:
      runWebServer: false
      webServerDelay: 10
    hashes:
      alg: 4
      min: 20
      max: 30
########################################## end ##########################################

###################################### begin bartik #####################################
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: bartik  # https://en.wikipedia.org/wiki/Jean_Bartik
  namespace: ctf
spec:
  schedule: "*/15 * * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: flags
              image: ghcr.io/hlesey/flags:1.0
              args:
                - --config=/app/config/config.yaml
              volumeMounts:
              - name: config
                mountPath: /app/config
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                name: cm-bartik
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-bartik
  namespace: ctf
data:
  config.yaml: |-
    server:
      runWebServer: false
      webServerDelay: 10
    hashes:
      alg: 3
      min: 10
      max: 20
########################################## end ##########################################

####################################### begin benz ######################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benz  # https://en.wikipedia.org/wiki/Karl_Benz
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benz
  template:
    metadata:
      labels:
        app: benz
    spec:
      containers:
        - name: flags
          image: ghcr.io/hlesey/flags:1.0
          args:
            - --config=/app/config/config.yaml
          volumeMounts:
          - name: config
            mountPath: /app/config
          livenessProbe:
            initialDelaySeconds: 0
            periodSeconds: 1
            httpGet:
              path: /
              port: 8080
      volumes:
        - name: config
          configMap:
            name: cm-benz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-benz
  namespace: ctf
data:
  config.yaml: |-
    server:
      initialDelay: 5
    hashes:
      alg: 1
      min: 20
      max: 30
########################################## end ##########################################

####################################### begin hertz ####################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hertz  #  https://en.wikipedia.org/wiki/Heinrich_Hertz
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hertz
  template:
    metadata:
      labels:
        app: hertz
    spec:
      containers:
        - name: flags
          image: ghcr.io/hlesey/flags:1.0
          command:
            - /app/flags<FIXME>
          args:
            - --config=/app/config/config.yaml
          volumeMounts:
          - name: config
            mountPath: /app/config
      volumes:
        - name: config
          configMap:
            name: cm-hertz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-hertz
  namespace: ctf
data:
  config.yaml: |-
    hashes:
      alg: 3
########################################## end ##########################################

##################################### begin blackburn ###################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackburn  # https://en.wikipedia.org/wiki/Elizabeth_Blackburn
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackburn
  template:
    metadata:
      labels:
        app: blackburn
    spec:
      containers:
        - name: flags
          image: ghcr.io/hlesey/flags:1.0
          args:
            - --config=/app/config/config.yaml
          volumeMounts:
          - name: config
            mountPath: /app/config
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
      volumes:
        - name: config
          configMap:
            name: cm-blackburn
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-blackburn
  namespace: ctf
data:
  config.yaml: |-
    stressTest:
      runStress: true
      memStepSize: 0Mi
      cpus: 1
########################################## end ##########################################

####################################### begin carson ####################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carson  # https://en.wikipedia.org/wiki/Rachel_Carson
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carson
  template:
    metadata:
      labels:
        app: carson
    spec:
      containers:
        - name: flags
          image: ghcr.io/hlesey/flags:1.0
          args:
            - --config=/app/config/config.yaml
          volumeMounts:
          - name: config
            mountPath: /app/config
          resources:
            limits:
              memory: 256Mi
              cpu: 90m
      volumes:
        - name: config
          configMap:
            name: cm-carson
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-carson
  namespace: ctf
data:
  config.yaml: |-
    hashes:
      alg: 1
      min: 10
      max: 20
    stressTest:
      runStress: true
      memTotal: 128Mi
      memStepSize: 16Mi
########################################## end ##########################################

####################################### begin secret ####################################
---
apiVersion: v1
kind: Secret
metadata:
  name: ctf-kubernetes
  namespace: kube-system
data:
  flag: VGhpcyBpcyBzdXBlciBzaW1wbGUK
########################################## end ##########################################
