
########################################## begin goldberg ##########################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goldberg  # https://en.wikipedia.org/wiki/Adele_Goldberg_(computer_scientist)
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goldberg
  template:
    metadata:
      labels:
        app: goldberg
    spec:
      containers:
      - image: hlesey/hash-go:<FIXME>
        name: hash-go
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: cm-goldberg
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-goldberg
  namespace: ctf
data:
  hash-go.yaml: |-
    initialDelay: 0 # initial delay before start the entire app
    webServerDelay: 0 # initial delay before start the webserver
    runWebServer: true # run the webserver
    webPort: 8080
    # Hashes
    displayHash: true # Display the hash flags
    allHashes: false  # Display all posible hashes
    algorithm: 0  # Hash alogorithm. From 0-4
    hashSalt: "aabbccdd" # Hash salt
    hashMin: 0  # Hash lower start
    hashMax: 10 # Hash upper end
    # Stress
    runStress: false # run cpu and memory stress
    memTotal: 32Mi # Total memory to be consumed. Memory will be consumed via multiple allocations.
    memStepSize: 4Mi #  Amount of memory to be consumed in each allocation
    memSleepDuration: 1000 # duration.Miliseconds -  Duration to sleep between allocations
    cpus: 0 # Total number of CPUs to utilize
---
apiVersion: v1
kind: Service
metadata:
  name: goldberg
  namespace: ctf
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
########################################## end ##########################################

####################################### begin idun ######################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idun
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idun
  template:
    metadata:
      labels:
        app: idun
    spec:
      containers:
      - image: hlesey/hash-go:1.0
        name: hash-go
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: cm-idun
      securityContext:
        runAsUser: 1000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-idun
  namespace: ctf
data:
  hash-go.yaml: |-
    initialDelay: 0 # initial delay before start the entire app
    webServerDelay: 0 # initial delay before start the webserver
    runWebServer: true # run the webserver
    webPort: 8080
    # Hashes
    displayHash: true # Display the hash flags
    allHashes: false  # Display all posible hashes
    algorithm: 2  # Hash alogorithm. From 0-4
    hashSalt: "aabbccdd" # Hash salt
    hashMin: 0  # Hash lower start
    hashMax: 10 # Hash upper end
    # Stress
    runStress: false # run cpu and memory stress
    memTotal: 32Mi # Total memory to be consumed. Memory will be consumed via multiple allocations.
    memStepSize: 4Mi #  Amount of memory to be consumed in each allocation
    memSleepDuration: 1000 # duration.Miliseconds -  Duration to sleep between allocations
    cpus: 0 # Total number of CPUs to utilize
---
apiVersion: v1
kind: Service
metadata:
  name: idun
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
########################################## end ##########################################

###################################### begin clarke #####################################
---
apiVersion: v1
kind: Pod
metadata:
  name: clarke  # https://en.wikipedia.org/wiki/Joan_Clarke
  namespace: ctf
spec:
  containers:
    - image: hlesey/hash-go:1.0
      name: hash-go
      volumeMounts:
      - name: config
        mountPath: /app/config
  volumes:
    - name: config
      configMap:
        name: cm-clarke
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-clarke
  namespace: ctf
data:
  hash-go.yaml: |-
    initialDelay: 0 # initial delay before start the entire app
    webServerDelay: 0 # initial delay before start the webserver
    runWebServer: true # run the webserver
    webPort: 8080
    # Hashes
    displayHash: true # Display the hash flags
    allHashes: false  # Display all posible hashes
    algorithm: 1  # Hash alogorithm. From 0-4
    hashSalt: "aabbccdd" # Hash salt
    hashMin: 10  # Hash lower start
    hashMax: 20 # Hash upper end
    # Stress
    runStress: true # run cpu and memory stress
    memTotal: 64Mi # Total memory to be consumed. Memory will be consumed via multiple allocations.
    memStepSize: 16Mi #  Amount of memory to be consumed in each allocation
    memSleepDuration: 1000 # duration.Miliseconds -  Duration to sleep between allocations
    cpus: 0 # Total number of CPUs to utilize
---
apiVersion: v1
kind: Service
metadata:
  name: clarke
  namespace: ctf
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
########################################## end ##########################################

###################################### begin darwin #####################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: darwin  # https://en.wikipedia.org/wiki/Charles_Darwin
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: darwin
  template:
    metadata:
      labels:
        app: darwin
    spec:
      containers:
        - image: hlesey/hash-go:1.0
          name: hash-go
          volumeMounts:
          - name: config
            mountPath: /app/config
      initContainers:
      - name: init-myapp
        image: busybox
        command: ['sh', '-c', 'until nslookup darwin; do echo waiting for myservice; sleep 2; done;']
      volumes:
        - name: config
          configMap:
            name: cm-darwin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-darwin
  namespace: ctf
data:
  hash-go.yaml: |-
    initialDelay: 0 # initial delay before start the entire app
    webServerDelay: 0 # initial delay before start the webserver
    runWebServer: true # run the webserver
    webPort: 8080
    # Hashes
    displayHash: true # Display the hash flags
    allHashes: false  # Display all posible hashes
    algorithm: 2  # Hash alogorithm. From 0-4
    hashSalt: "aabbccdd" # Hash salt
    hashMin: 0  # Hash lower start
    hashMax: 10 # Hash upper end
    # Stress
    runStress: false # run cpu and memory stress
    memTotal: 32Mi # Total memory to be consumed. Memory will be consumed via multiple allocations.
    memStepSize: 4Mi #  Amount of memory to be consumed in each allocation
    memSleepDuration: 1000 # duration.Miliseconds -  Duration to sleep between allocations
    cpus: 0 # Total number of CPUs to utilize
---
########################################## end ##########################################

##################################### begin dijkstra ####################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dijkstra  # https://en.wikipedia.org/wiki/Edsger_W._Dijkstra
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dijkstra
  template:
    metadata:
      labels:
        app: dijkstra
    spec:
      containers:
        - image: hlesey/hash-go:1.0
          name: hash-go
          volumeMounts:
          - name: config
            mountPath: /app/config
          readinessProbe:
            httpGet:
              path: /
              port: 80
      volumes:
        - name: config
          configMap:
            name: cm-dijkstra
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-dijkstra
  namespace: ctf
data:
  hash-go.yaml: |-
    initialDelay: 0 # initial delay before start the entire app
    webServerDelay: 0 # initial delay before start the webserver
    runWebServer: true # run the webserver
    webPort: 8080
    # Hashes
    displayHash: true # Display the hash flags
    allHashes: false  # Display all posible hashes
    algorithm: 4  # Hash alogorithm. From 0-4
    hashSalt: "aabbccdd" # Hash salt
    hashMin: 0  # Hash lower start
    hashMax: 10 # Hash upper end
    # Stress
    runStress: false # run cpu and memory stress
    memTotal: 32Mi # Total memory to be consumed. Memory will be consumed via multiple allocations.
    memStepSize: 4Mi #  Amount of memory to be consumed in each allocation
    memSleepDuration: 1000 # duration.Miliseconds -  Duration to sleep between allocations
    cpus: 0 # Total number of CPUs to utilize
########################################## end ##########################################

###################################### begin banach #####################################
---
apiVersion: batch/v1
kind: Job
metadata:
  name: banach  # https://en.wikipedia.org/wiki/Stefan_Banach
  namespace: ctf
spec:
  template:
    spec:
      containers:
        - image: hlesey/hash-go:1.0
          name: banach
          volumeMounts:
          - name: config
            mountPath: /app/config
      restartPolicy: Never
      volumes:
        - name: config
          configMap:
            name: cm-banach
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-banach
  namespace: ctf
data:
  hash-go.yaml: |-
    initialDelay: 0 # initial delay before start the entire app
    webServerDelay: 0 # initial delay before start the webserver
    runWebServer: true # run the webserver
    webPort: 8080
    # Hashes
    displayHash: true # Display the hash flags
    allHashes: false  # Display all posible hashes
    algorithm: 4  # Hash alogorithm. From 0-4
    hashSalt: "aabbccdd" # Hash salt
    hashMin: 20  # Hash lower start
    hashMax: 30 # Hash upper end
    # Stress
    runStress: false # run cpu and memory stress
    memTotal: 32Mi # Total memory to be consumed. Memory will be consumed via multiple allocations.
    memStepSize: 4Mi #  Amount of memory to be consumed in each allocation
    memSleepDuration: 1000 # duration.Miliseconds -  Duration to sleep between allocations
    cpus: 0 # Total number of CPUs to utilize
########################################## end ##########################################

####################################### begin benz ######################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benz  # https://en.wikipedia.org/wiki/Karl_Benz
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: benz
  template:
    metadata:
      labels:
        app: benz
    spec:
      containers:
        - image: hlesey/hash-go:1.0
          name: benz
          volumeMounts:
          - name: config
            mountPath: /app/config
          livenessProbe:
            initialDelaySeconds: 1
            failureThreshold: 1
            httpGet:
              path: /
              port: 8080
      volumes:
        - name: config
          configMap:
            name: cm-benz
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-benz
  namespace: ctf
data:
  hash-go.yaml: |-
    initialDelay: 20 # initial delay before start the entire app
    webServerDelay: 0 # initial delay before start the webserver
    runWebServer: true # run the webserver
    webPort: 8080
    # Hashes
    displayHash: true # Display the hash flags
    allHashes: false  # Display all posible hashes
    algorithm: 1  # Hash alogorithm. From 0-4
    hashSalt: "aabbccdd" # Hash salt
    hashMin: 20  # Hash lower start
    hashMax: 30 # Hash upper end
    # Stress
    runStress: false # run cpu and memory stress
    memTotal: 32Mi # Total memory to be consumed. Memory will be consumed via multiple allocations.
    memStepSize: 4Mi #  Amount of memory to be consumed in each allocation
    memSleepDuration: 1000 # duration.Miliseconds -  Duration to sleep between allocations
    cpus: 0 # Total number of CPUs to utilize
---
apiVersion: v1
kind: Service
metadata:
  name: benz
  namespace: ctf
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
########################################## end ##########################################

##################################### begin blackburn ###################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackburn  # https://en.wikipedia.org/wiki/Elizabeth_Blackburn
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackburn
  template:
    metadata:
      labels:
        app: blackburn
    spec:
      containers:
        - image: hlesey/hash-go:1.0
          name: blackburn
          volumeMounts:
          - name: config
            mountPath: /app/config
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
      volumes:
        - name: config
          configMap:
            name: cm-blackburn
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-blackburn
  namespace: ctf
data:
  hash-go.yaml: |-
    initialDelay: 0 # initial delay before start the entire app
    webServerDelay: 0 # initial delay before start the webserver
    runWebServer: true # run the webserver
    webPort: 8080
    # Hashes
    displayHash: true # Display the hash flags
    allHashes: false  # Display all posible hashes
    algorithm: 0  # Hash alogorithm. From 0-4
    hashSalt: "aabbccdd" # Hash salt
    hashMin: 0  # Hash lower start
    hashMax: 10 # Hash upper end
    # Stress
    runStress: true # run cpu and memory stress
    memTotal: 32Mi # Total memory to be consumed. Memory will be consumed via multiple allocations.
    memStepSize: 0Mi #  Amount of memory to be consumed in each allocation
    memSleepDuration: 1000 # duration.Miliseconds -  Duration to sleep between allocations
    cpus: 1 # Total number of CPUs to utilize
########################################## end ##########################################

####################################### begin carson ####################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carson  # https://en.wikipedia.org/wiki/Rachel_Carson
  namespace: ctf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carson
  template:
    metadata:
      labels:
        app: carson
    spec:
      containers:
        - image: hlesey/hash-go:1.0
          name: carson
          volumeMounts:
          - name: config
            mountPath: /app/config
          resources:
            limits:
              memory: 256Mi
              cpu: 90m
      volumes:
        - name: config
          configMap:
            name: cm-carson
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-carson
  namespace: ctf
data:
  hash-go.yaml: |-
    initialDelay: 0 # initial delay before start the entire app
    webServerDelay: 0 # initial delay before start the webserver
    runWebServer: true # run the webserver
    webPort: 8080
    # Hashes
    displayHash: true # Display the hash flags
    allHashes: false  # Display all posible hashes
    algorithm: 1  # Hash alogorithm. From 0-4
    hashSalt: "aabbccdd" # Hash salt
    hashMin: 10  # Hash lower start
    hashMax: 20 # Hash upper end
    # Stress
    runStress: true # run cpu and memory stress
    memTotal: 128Mi # Total memory to be consumed. Memory will be consumed via multiple allocations.
    memStepSize: 16Mi #  Amount of memory to be consumed in each allocation
    memSleepDuration: 1000 # duration.Miliseconds -  Duration to sleep between allocations
    cpus: 0 # Total number of CPUs to utilize
########################################## end ##########################################
---
####################################### begin secret ####################################
apiVersion: v1
kind: Secret
metadata:
  name: ctf-kubernetes
  namespace: kube-system
data:
  flag: VGhpcyBpcyBzdXBlciBzaW1wbGUK
########################################## end ##########################################
